### PR TITLE
Slim organizing files and directories

### PR DESCRIPTION
**Pull request by SlimoTECH**

### CODE REVIEW

**Comment by devmunro** [comment]
Just tired to test seems to come up with some errors - 

**Compiled with problems:X**

_ERROR in ./src/App.js 13:0-52_

Module not found: Error: Can't resolve './components/Add Job/PostJob' in 'C:\Users\track\Desktop\helper-project\src'

_ERROR in ./src/App.js 14:0-50_

Module not found: Error: Can't resolve './components/Add Job/Sucess' in 'C:\Users\track\Desktop\helper-project\src'

_ERROR in ./src/components/NavBar/hamburger.js 7:0-45_

Module not found: Error: Can't resolve '../Account/logout' in 'C:\Users\track\Desktop\helper-project\src\components\NavBar'

_ERROR in ./src/components/NavBar/navBar.js 6:0-45_

Module not found: Error: Can't resolve '../Account/logout' in 'C:\Users\track\Desktop\helper-project\src\components\NavBar'

**Review by SlimoTECH — COMMENTED** [review]
Hmmm

**Comment by devmunro** [comment]
passed to another branch - want to watch football

**Comment by devmunro** [comment]
passed to another branch

**Pull request closed without merging**
